declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_API_KEY_FIREBASE: string;
    NEXT_PUBLIC_AUTH_DOMAIN_FIREBASE: string;
    NEXT_PUBLIC_PROJECT_ID_FIREBASE: string;
    NEXT_PUBLIC_STORAGE_BUCKET_FIREBASE: string;
    NEXT_PUBLIC_MESSAGING_SENDER_ID_FIREBASE: string;
    NEXT_PUBLIC_APP_ID_FIREBASE: string;
    NEXT_PUBLIC_MEASUREMENT_ID_FIREBASE: string;
    NEXT_PUBLIC_SECRET_KEY: string;
    FIREBASE_PRIVATE_KEY: string;
    FIREBASE_CLIENT_EMAIL: string;
    AUTH_API_URL: string;
  }
}
